import { TPhoto } from "@/types";

export const PhotosData: TPhoto[] = [
  {
    name: "Red Bench",
    category: "people",
    price: 3.89,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/9507099/pexels-photo-9507099.jpeg",
      alt: "Red Bench",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    name: "Egg Balloon",
    category: "food",
    price: 93.89,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/5623042/pexels-photo-5623042.jpeg",
      alt: "Egg Ballon",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Man",
    category: "people",
    price: 100,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/12092806/pexels-photo-12092806.jpeg",
      alt: "Man",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Architecture",
    category: "landmarks",
    price: 101,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/1639834/pexels-photo-1639834.jpeg",
      alt: "Architecture",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Lion",
    category: "pets",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/2220336/pexels-photo-2220336.jpeg",
      alt: "Architecture",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Chess",
    category: "pets",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/260024/pexels-photo-260024.jpeg",
      alt: "Architecture",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 1",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 800,
    },
    image: {
      src: "https://images.pexels.com/photos/12079516/pexels-photo-12079516.jpeg",
      alt: "Nature",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    name: "Nature 2",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/12166061/pexels-photo-12166061.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 3",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/3551252/pexels-photo-3551252.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 4",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/11660966/pexels-photo-11660966.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 5",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/12125347/pexels-photo-12125347.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 6",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/12017866/pexels-photo-12017866.jpeg",
      alt: "Nature",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    name: "Nature 7",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/11581374/pexels-photo-11581374.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 8",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/12078050/pexels-photo-12078050.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 9",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/11577525/pexels-photo-11577525.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 10",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/12115113/pexels-photo-12115113.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 11",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/7296698/pexels-photo-7296698.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 12",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/11502645/pexels-photo-11502645.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 13",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/11946376/pexels-photo-11946376.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 14",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/1634872/pexels-photo-1634872.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Nature 15",
    category: "nature",
    price: 20,
    currency: "USD",
    dimmentions: {
      width: 1020,
      height: 1020,
    },
    image: {
      src: "https://images.pexels.com/photos/10406845/pexels-photo-10406845.jpeg",
      alt: "Nature",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Samurai King Restling",
    category: "pets",
    price: 101,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/237272/pexels-photo-237272.jpeg",
      alt: "Samurai King Restling",
    },
    bestseller: false,
    featured: true,
    details: {
      dimmentions: {
        width: 1020,
        height: 800,
      },
      size: 15000,
      description:
        "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely scrambled part of Cicero's De Finibus in order to provide placeholder text to mockup various fonts for a type specimen book.So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely scrambled part of Cicero's De Finibus in order to provide placeholder text to mockup various fonts for a type specimen book.So how did the classical Latin become so incoherent? According to McClintock.",
      recommendations: [
        {
          src: "https://images.pexels.com/photos/9507099/pexels-photo-9507099.jpeg",
          alt: "",
        },
        {
          src: "https://images.pexels.com/photos/5623042/pexels-photo-5623042.jpeg",
          alt: "",
        },
        {
          src: "https://images.pexels.com/photos/1639834/pexels-photo-1639834.jpeg",
          alt: "",
        },
      ],
    },
  },
];
